name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: Static build
      run: make static

    - name: Shared build
      run: make shared

    - name: Build package
      run: make package

    - name: Install package
      run: sudo apt install ./newlib.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: build
          path: |
            ./contrib/sdk/sources/newlib/libc/libdll.a
            ./contrib/sdk/sources/newlib/libc/libc.a
            ./contrib/sdk/sources/newlib/libc/libc.dll
            ./contrib/sdk/sources/newlib/libc/libc.dll.a
            ./newlib.deb
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: egor00f/install-kolibrios-toolchain-action@v1.1
      
      - name: Static build
        run: make tests

